spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cdupfs
    password: 521314
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081


# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 指定mybatis的sql语句文件
  type-aliases-package: com.example.demo.pojo  # 指定别名包路径
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # 日志实现类
